@extends('layouts.pegawai')
@section('title','Surat Masuk')
@section('content')
<div class="container-fluid employee-page">
    <div class="page-header"><div><h2><i class="bi bi-envelope-arrow-down-fill text-primary me-2"></i>Surat Masuk</h2><p class="text-muted mb-0">Catat surat, pantau approval Admin, dan kelola perbaikannya.</p></div><a href="{{ route('pegawai.surat-masuk.create') }}" class="btn btn-primary"><i class="bi bi-plus-circle me-2"></i>Catat Surat Masuk</a></div>
    <div class="metric-grid">@foreach([['Total',$stats['total'],'bi-files','primary'],['Draft',$stats['draft'],'bi-file-earmark','secondary'],['Menunggu Verifikasi',$stats['menunggu_verifikasi'],'bi-hourglass-split','warning'],['Disetujui Admin',$stats['disetujui'],'bi-shield-check','success'],['Perlu Perbaikan',$stats['perbaikan'],'bi-exclamation-triangle','danger']] as [$label,$value,$icon,$color])<div class="metric-card"><span class="metric-icon bg-{{ $color }}-subtle text-{{ $color }}"><i class="bi {{ $icon }}"></i></span><div><strong>{{ $value }}</strong><small>{{ $label }}</small></div></div>@endforeach</div>
    <div class="data-card">
        <form method="GET" class="filter-bar"><div class="search-control"><i class="bi bi-search"></i><input name="keyword" value="{{ request('keyword') }}" placeholder="Cari nomor, perihal, atau asal surat"></div><select name="status"><option value="">Semua status</option>@foreach(['draft'=>'Draft / Belum Dikirim','diajukan'=>'Menunggu Verifikasi Admin','diverifikasi'=>'Disetujui Admin','dikembalikan'=>'Perlu Perbaikan','diproses'=>'Sedang Diproses','diteruskan_ke_pimpinan'=>'Diteruskan ke Pimpinan','selesai'=>'Selesai'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i>Filter</button>@if(request()->hasAny(['keyword','status']))<a href="{{ route('pegawai.surat-masuk.index') }}" class="btn btn-outline-secondary"><i class="bi bi-x-lg"></i></a>@endif</form>
        <div class="table-responsive"><table class="table compact-table incoming-table mb-0">
            <thead><tr><th>No</th><th>Nomor &amp; Perihal</th><th>Asal &amp; Tujuan</th><th>Tanggal</th><th>Lampiran</th><th>Status Verifikasi</th><th class="text-end">Aksi</th></tr></thead>
            <tbody>@forelse($suratMasuk as $surat)<tr>
                <td>{{ $suratMasuk->firstItem()+$loop->index }}</td>
                <td><span class="cell-title">{{ $surat->nomor_surat }}</span><span class="cell-meta">{{ $surat->perihal }}</span></td>
                <td><span class="cell-title">{{ $surat->asal_surat ?: '-' }}</span><span class="cell-meta"><i class="bi bi-arrow-right me-1"></i>{{ $surat->tujuan_surat ?: '-' }}</span></td>
                <td><span class="cell-title">{{ $surat->tanggal_surat?->translatedFormat('d M Y') }}</span><span class="cell-meta">Diubah {{ $surat->updated_at->diffForHumans() }}</span></td>
                <td>@if($surat->file_path)<a href="{{ route('surat.lampiran',$surat) }}" class="attachment-chip" title="Buka lampiran"><i class="bi bi-paperclip"></i>{{ strtoupper(pathinfo($surat->file_path,PATHINFO_EXTENSION)) }}</a>@else<span class="cell-meta">Tidak ada</span>@endif</td>
                <td><span class="badge rounded-pill bg-{{ $surat->status_badge }}">{{ $surat->status_label }}</span><span class="cell-meta {{ $surat->status==='dikembalikan'?'text-danger':'text-muted' }}">{{ match($surat->status){'draft'=>'Belum dikirim ke Admin','diajukan','menunggu'=>'Menunggu approval Admin','diverifikasi'=>'Telah disetujui Admin','dikembalikan'=>'Dikembalikan untuk diperbaiki','diproses'=>'Sudah diverifikasi dan diproses','diteruskan_ke_pimpinan'=>'Sudah diteruskan oleh Admin','selesai'=>'Proses telah selesai',default=>$surat->status_label} }}</span>@if($surat->catatan_admin)<span class="cell-meta text-danger" title="{{ $surat->catatan_admin }}">Catatan: {{ Str::limit($surat->catatan_admin,45) }}</span>@endif</td>
                <td><div class="row-actions"><a href="{{ route('pegawai.surat-masuk.show',$surat) }}" class="btn btn-outline-primary" title="Detail"><i class="bi bi-eye"></i></a>@if(in_array($surat->status,['draft','dikembalikan']))<a href="{{ route('pegawai.surat-masuk.edit',$surat) }}" class="btn btn-outline-warning" title="Edit"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('pegawai.surat-masuk.kirim',$surat) }}" onsubmit="return confirm('Kirim surat ke Admin untuk diverifikasi?')">@csrf @method('PUT')<button class="btn btn-outline-success" title="Kirim ke Admin"><i class="bi bi-send"></i></button></form><form method="POST" action="{{ route('pegawai.surat-masuk.destroy',$surat) }}" onsubmit="return confirm('Pindahkan surat ini ke sampah?')">@csrf @method('DELETE')<button class="btn btn-outline-danger" title="Hapus"><i class="bi bi-trash"></i></button></form>@endif</div></td>
            </tr>@empty<tr><td colspan="7"><div class="empty-state"><i class="bi bi-inbox"></i><h5>Belum ada surat masuk</h5><p>Catat surat baru atau ubah filter pencarian.</p></div></td></tr>@endforelse</tbody>
        </table></div>
        <div class="data-footer"><span>{{ $suratMasuk->firstItem() ?? 0 }}&ndash;{{ $suratMasuk->lastItem() ?? 0 }} dari {{ $suratMasuk->total() }} surat</span>{{ $suratMasuk->links() }}</div>
    </div>
</div>
@endsection
@push('styles')<style>.incoming-table{min-width:1120px}.attachment-chip{display:inline-flex;align-items:center;gap:5px;padding:6px 9px;border-radius:9px;background:#eaf3fb;color:#0f4c81;text-decoration:none;font-size:12px;font-weight:700}</style>@endpush
