@php($current=$unitKerja ?? null)
@if($errors->any())<div class="alert alert-danger"><strong>Periksa kembali data unit kerja.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="unit-form-card"><div class="form-heading"><span><i class="bi bi-building"></i></span><div><h4>Informasi Unit Kerja</h4><p>Kode dan nama wajib diisi serta tidak boleh sama dengan unit lain.</p></div></div><div class="row g-3">
<div class="col-md-4"><label class="form-label">Kode Unit <span class="text-danger">*</span></label><input name="kode" maxlength="30" required value="{{ old('kode',$current?->kode) }}" class="form-control @error('kode') is-invalid @enderror" placeholder="Contoh: UMUM">@error('kode')<div class="invalid-feedback">{{ $message }}</div>@enderror<small class="form-text">Otomatis disimpan sebagai huruf kapital.</small></div>
<div class="col-md-8"><label class="form-label">Nama Unit Kerja <span class="text-danger">*</span></label><input name="nama" maxlength="150" required value="{{ old('nama',$current?->nama) }}" class="form-control @error('nama') is-invalid @enderror" placeholder="Contoh: Bagian Administrasi Umum">@error('nama')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-12"><label class="form-label">Deskripsi</label><textarea name="deskripsi" maxlength="1000" rows="5" class="form-control @error('deskripsi') is-invalid @enderror" placeholder="Jelaskan fungsi atau ruang lingkup unit kerja">{{ old('deskripsi',$current?->deskripsi) }}</textarea><div class="form-hint"><span>Opsional, maksimal 1.000 karakter.</span><span id="unitDescriptionCount">0/1000</span></div>@error('deskripsi')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="form-note"><i class="bi bi-info-circle"></i><span>Unit yang sudah memiliki pegawai dapat diperbarui, tetapi tidak dapat dihapus.</span></div><div class="form-actions"><a href="{{ route('admin.unit.kerja.index') }}" class="btn btn-light border">Batal</a><button class="btn btn-primary"><i class="bi bi-save me-2"></i>{{ $editing?'Simpan Perubahan':'Simpan Unit Kerja' }}</button></div></div>
@once
@push('styles')<style>.unit-form{max-width:920px;margin:0 auto}.unit-form-card{background:#fff;border:1px solid #e5eaf0;border-radius:18px;padding:28px;box-shadow:0 9px 26px rgba(15,76,129,.06)}.form-heading{display:flex;gap:14px;align-items:center;padding-bottom:19px;margin-bottom:22px;border-bottom:1px solid #edf1f5}.form-heading>span{width:44px;height:44px;border-radius:12px;background:#edf6ff;color:#0f4c81;display:grid;place-items:center;font-size:20px}.form-heading h4{margin:0 0 3px;font-size:19px;font-weight:700}.form-heading p{margin:0;color:#718096;font-size:13px}.unit-form .form-label{font-weight:650;color:#334155}.unit-form .form-control{min-height:48px;border-color:#dbe2ea;border-radius:11px}.unit-form textarea.form-control{min-height:130px}.form-text,.form-hint{font-size:12px;color:#8491a3;margin-top:5px}.form-hint{display:flex;justify-content:space-between}.form-note{display:flex;gap:9px;padding:14px;margin-top:22px;background:#edf6ff;color:#174b75;border-radius:11px;font-size:13px}.form-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:22px}.form-actions .btn{min-width:155px;border-radius:10px}@media(max-width:600px){.unit-form-card{padding:20px}.form-actions{flex-direction:column-reverse}.form-actions .btn{width:100%}}</style>@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const f=document.querySelector('textarea[name="deskripsi"]'),c=document.getElementById('unitDescriptionCount');if(!f||!c)return;const u=()=>c.textContent=`${f.value.length}/1000`;f.addEventListener('input',u);u();});</script>@endpush
@endonce
