@extends('layouts.admin')
@section('title', 'Data Unit Kerja')
@section('content')
<div class="page-header fade-up"><div><h2><i class="bi bi-building-fill text-primary me-2"></i>Data Unit Kerja</h2><p class="text-muted mb-0">Kelola unit organisasi dan pantau penempatan pegawai.</p></div><a href="{{ route('admin.unit.kerja.create') }}" class="btn btn-primary"><i class="bi bi-plus-circle me-2"></i>Tambah Unit Kerja</a></div>

<div class="unit-stats mb-4 fade-up">
@foreach([['Total Unit',$totalUnit,'bi-buildings','primary'],['Digunakan',$unitTerpakai,'bi-people-fill','success'],['Belum Digunakan',$unitKosong,'bi-exclamation-circle','warning']] as [$label,$value,$icon,$color])
<div class="unit-stat"><div><h3>{{ $value }}</h3><span>{{ $label }}</span></div><i class="bi {{ $icon }} text-{{ $color }}"></i></div>
@endforeach
</div>

<div class="unit-card fade-up">
    <div class="unit-toolbar"><div><h5>Daftar Unit Kerja</h5><small>{{ $unitKerja->total() }} data sesuai pencarian</small></div><form method="GET" class="unit-search"><i class="bi bi-search"></i><input name="keyword" value="{{ request('keyword') }}" placeholder="Cari kode, nama, atau deskripsi...">@if(request('keyword'))<a href="{{ route('admin.unit.kerja.index') }}"><i class="bi bi-x-lg"></i></a>@endif</form></div>
    <div class="table-responsive"><table class="table align-middle mb-0 unit-table"><thead><tr><th width="65">No</th><th width="145">Kode</th><th>Nama Unit Kerja</th><th>Deskripsi</th><th width="130">Pegawai</th><th width="155">Aksi</th></tr></thead><tbody>
    @forelse($unitKerja as $item)
    <tr><td>{{ $unitKerja->firstItem()+$loop->index }}</td><td><span class="code-badge">{{ $item->kode }}</span></td><td><strong>{{ $item->nama }}</strong></td><td><span class="description-text">{{ $item->deskripsi ?: 'Belum ada deskripsi' }}</span></td><td><span class="usage-badge {{ $item->pegawai_count ? 'used':'empty' }}"><i class="bi bi-people me-1"></i>{{ $item->pegawai_count }}</span></td><td><div class="unit-actions">
        <a class="action-view" href="{{ route('admin.unit.kerja.show',$item->id) }}" title="Detail"><i class="bi bi-eye"></i></a><a class="action-edit" href="{{ route('admin.unit.kerja.edit',$item->id) }}" title="Edit"><i class="bi bi-pencil"></i></a>
        @if($item->pegawai_count===0)<form method="POST" action="{{ route('admin.unit.kerja.destroy',$item->id) }}" onsubmit="return confirm('Hapus unit kerja ini?')">@csrf @method('DELETE')<button class="action-delete" title="Hapus"><i class="bi bi-trash"></i></button></form>@else<button class="action-disabled" disabled title="Masih digunakan pegawai"><i class="bi bi-lock"></i></button>@endif
    </div></td></tr>
    @empty<tr><td colspan="6"><div class="empty-state"><i class="bi bi-building-x"></i><strong>{{ request('keyword') ? 'Unit kerja tidak ditemukan':'Belum ada unit kerja' }}</strong><span>{{ request('keyword') ? 'Coba gunakan kata pencarian lainnya.':'Tambahkan unit kerja pertama untuk mulai mengatur penempatan pegawai.' }}</span></div></td></tr>@endforelse
    </tbody></table></div>
    <div class="unit-footer"><span>Menampilkan {{ $unitKerja->firstItem() ?? 0 }}–{{ $unitKerja->lastItem() ?? 0 }} dari {{ $unitKerja->total() }} unit</span>{{ $unitKerja->links() }}</div>
</div>
@endsection
@push('styles')<style>
.unit-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.unit-stat{background:#fff;border:1px solid #e5eaf0;border-radius:16px;padding:20px 22px;display:flex;align-items:center;justify-content:space-between;box-shadow:0 8px 22px rgba(15,76,129,.05)}.unit-stat h3{font-size:28px;font-weight:750;margin:0;color:#17233b}.unit-stat span{font-size:13px;color:#718096}.unit-stat>i{font-size:27px}.unit-card{background:#fff;border:1px solid #e5eaf0;border-radius:18px;overflow:hidden;box-shadow:0 9px 26px rgba(15,76,129,.06)}.unit-toolbar{padding:20px 24px;display:flex;align-items:center;justify-content:space-between;gap:18px;border-bottom:1px solid #e9eef3}.unit-toolbar h5{margin:0;font-weight:700}.unit-toolbar small{color:#8491a3}.unit-search{position:relative;width:min(390px,100%)}.unit-search>i{position:absolute;left:14px;top:50%;transform:translateY(-50%);color:#94a3b8}.unit-search input{width:100%;height:46px;padding:10px 42px;border:1px solid #dbe2ea;border-radius:11px;outline:none}.unit-search input:focus{border-color:#0f4c81;box-shadow:0 0 0 .18rem rgba(15,76,129,.1)}.unit-search a{position:absolute;right:14px;top:50%;transform:translateY(-50%);color:#8491a3}.unit-table{min-width:900px}.unit-table th{background:#f8fafc;padding:14px 16px;color:#475569;font-size:12px;text-transform:uppercase}.unit-table td{padding:15px 16px;border-color:#edf1f5}.code-badge,.usage-badge{display:inline-flex;align-items:center;padding:6px 10px;border-radius:8px;font-size:12px;font-weight:700}.code-badge{background:#edf6ff;color:#0f4c81}.usage-badge.used{background:#dcfce7;color:#166534}.usage-badge.empty{background:#f1f5f9;color:#64748b}.description-text{display:block;max-width:370px;color:#64748b;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.unit-actions{display:flex;gap:7px}.unit-actions form{margin:0}.unit-actions a,.unit-actions button{width:36px;height:36px;border:0;border-radius:9px;display:grid;place-items:center;text-decoration:none}.action-view{background:#e0f2fe;color:#0369a1}.action-edit{background:#fef3c7;color:#b45309}.action-delete{background:#fee2e2;color:#b91c1c}.action-disabled{background:#f1f5f9;color:#94a3b8}.unit-footer{padding:17px 24px;display:flex;align-items:center;justify-content:space-between;color:#718096;font-size:13px;border-top:1px solid #edf1f5}.unit-footer .pagination{margin:0}.empty-state{text-align:center;padding:58px 20px;color:#8491a3}.empty-state i,.empty-state strong,.empty-state span{display:block}.empty-state i{font-size:45px;margin-bottom:10px}.empty-state strong{color:#475569}@media(max-width:768px){.unit-stats{grid-template-columns:1fr}.unit-toolbar,.unit-footer{align-items:stretch;flex-direction:column}.unit-search{width:100%;text-align:center}}
</style>@endpush
