@extends('layouts.umum')
@section('title', 'Profil Saya')
@section('content')
<div class="profile-page">
    <div class="profile-heading"><div><h2><i class="bi bi-person-circle text-primary me-2"></i>Profil Saya</h2><p>Kelola identitas, kontak pengajuan, dan keamanan akun Anda.</p></div><span class="badge rounded-pill text-bg-primary">Pengguna Umum</span></div>

    @if(session('status'))<div class="alert alert-success alert-dismissible fade show"><i class="bi bi-check-circle-fill me-2"></i>{{ ['password-updated'=>'Password berhasil diperbarui.','photo-updated'=>'Foto profil berhasil diperbarui.','photo-deleted'=>'Foto profil berhasil dihapus.','profile-updated'=>'Profil berhasil diperbarui.'][session('status')] ?? 'Perubahan berhasil disimpan.' }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif

    <div class="row g-4">
        <aside class="col-lg-4">
            <div class="card border-0 shadow-sm profile-summary"><div class="card-body p-4 text-center">
                <div class="profile-avatar">@if($user->profile_photo_path)<img src="{{ asset('storage/'.$user->profile_photo_path) }}" alt="Foto profil {{ $user->name }}">@else{{ strtoupper(substr($user->name,0,1)) }}@endif</div>
                <div class="photo-actions mb-3"><form action="{{ route('profile.photo.update') }}" method="POST" enctype="multipart/form-data" id="photoForm">@csrf @method('PATCH')<label for="profilePhoto" class="btn btn-sm btn-outline-primary"><i class="bi bi-camera me-1"></i>{{ $user->profile_photo_path ? 'Ganti Foto' : 'Tambah Foto' }}</label><input id="profilePhoto" type="file" name="photo" class="d-none" accept="image/jpeg,image/png,image/webp" onchange="document.getElementById('photoForm').submit()"></form>@if($user->profile_photo_path)<form action="{{ route('profile.photo.destroy') }}" method="POST" onsubmit="return confirm('Hapus foto profil?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash me-1"></i>Hapus</button></form>@endif</div>
                @error('photo')<div class="alert alert-danger small py-2">{{ $message }}</div>@enderror
                <h4 class="fw-bold mb-1">{{ $user->name }}</h4><p class="text-muted mb-3 profile-email">{{ $user->email }}</p><div class="account-state"><i class="bi bi-shield-check"></i>Akun aktif</div><hr><div class="summary-details"><div><span>Bergabung</span><b>{{ $user->created_at?->format('d M Y') }}</b></div><div><span>Jenis akun</span><b>Masyarakat Umum</b></div><div><span>Kontak</span><b>{{ $user->phone ?: 'Belum dilengkapi' }}</b></div></div></div></div>
            <div class="profile-stats mt-3"><div><strong>{{ $statistik['total'] }}</strong><span>Total</span></div><div><strong>{{ $statistik['aktif'] }}</strong><span>Diproses</span></div><div><strong>{{ $statistik['selesai'] }}</strong><span>Selesai</span></div></div>
            <div class="alert alert-primary small mt-3 mb-0"><i class="bi bi-info-circle-fill me-2"></i>Kontak dan organisasi pada profil akan digunakan sebagai isian awal pengajuan baru.</div>
        </aside>

        <div class="col-lg-8">
            <div class="card border-0 shadow-sm mb-4 profile-card"><div class="card-header bg-white p-4"><h5 class="fw-bold mb-1"><i class="bi bi-person-lines-fill text-primary me-2"></i>Informasi Pribadi</h5><p class="text-muted small mb-0">Nama dan email dipakai sebagai identitas resmi akun.</p></div><div class="card-body p-4">
                <form method="POST" action="{{ route('profile.update') }}">@csrf @method('PATCH')
                    <div class="row g-3">
                        <div class="col-md-6"><label class="form-label">Nama Lengkap <span class="text-danger">*</span></label><input name="name" value="{{ old('name',$user->name) }}" maxlength="255" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-md-6"><label class="form-label">Email <span class="text-danger">*</span></label><input type="email" name="email" value="{{ old('email',$user->email) }}" class="form-control @error('email') is-invalid @enderror" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-md-6"><label class="form-label">Nomor Telepon/WhatsApp</label><input type="tel" name="phone" value="{{ old('phone',$user->phone) }}" maxlength="25" class="form-control @error('phone') is-invalid @enderror" placeholder="0812 3456 7890">@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-md-6"><label class="form-label">Instansi/Organisasi</label><input name="organization" value="{{ old('organization',$user->organization) }}" maxlength="255" class="form-control @error('organization') is-invalid @enderror" placeholder="Opsional untuk pengajuan perorangan">@error('organization')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-12"><label class="form-label">Alamat</label><textarea name="address" rows="3" maxlength="1000" class="form-control @error('address') is-invalid @enderror" placeholder="Alamat domisili atau alamat korespondensi">{{ old('address',$user->address) }}</textarea>@error('address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    </div><div class="text-end mt-4"><button class="btn btn-primary px-4"><i class="bi bi-save me-2"></i>Simpan Profil</button></div>
                </form>
            </div></div>

            <div class="card border-0 shadow-sm mb-4 profile-card"><div class="card-header bg-white p-4"><h5 class="fw-bold mb-1"><i class="bi bi-key-fill text-warning me-2"></i>Keamanan Akun</h5><p class="text-muted small mb-0">Gunakan password baru yang kuat dan tidak digunakan pada layanan lain.</p></div><div class="card-body p-4">
                <form method="POST" action="{{ route('profile.password.update') }}">@csrf @method('PUT')<div class="row g-3"><div class="col-12"><label class="form-label">Password Saat Ini</label><input type="password" name="current_password" autocomplete="current-password" class="form-control @error('current_password','updatePassword') is-invalid @enderror" required>@error('current_password','updatePassword')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">Password Baru</label><input type="password" name="password" autocomplete="new-password" class="form-control @error('password','updatePassword') is-invalid @enderror" required>@error('password','updatePassword')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">Konfirmasi Password</label><input type="password" name="password_confirmation" autocomplete="new-password" class="form-control" required></div></div><div class="text-end mt-4"><button class="btn btn-warning px-4"><i class="bi bi-key me-2"></i>Ubah Password</button></div></form>
            </div></div>

            <div class="card border-danger-subtle shadow-sm profile-card"><div class="card-header bg-danger-subtle p-4"><h5 class="fw-bold text-danger mb-1"><i class="bi bi-person-x-fill me-2"></i>Nonaktifkan Akun</h5><p class="small mb-0 text-danger-emphasis">Akun tidak dapat digunakan untuk login, tetapi histori pengajuan tetap disimpan.</p></div><div class="card-body p-4"><form action="{{ route('profile.destroy') }}" method="POST" onsubmit="return confirm('Yakin ingin menonaktifkan akun ini?')">@csrf @method('DELETE')<label class="form-label">Konfirmasi dengan password</label><div class="row g-2"><div class="col-md"><input type="password" name="password" class="form-control @error('password','userDeletion') is-invalid @enderror" placeholder="Masukkan password saat ini" required>@error('password','userDeletion')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-auto"><button class="btn btn-outline-danger h-100"><i class="bi bi-person-x me-2"></i>Nonaktifkan Akun</button></div></div></form></div></div>
        </div>
    </div>
</div>
@endsection
@push('styles')<style>
.profile-page{max-width:1180px;margin:auto}.profile-heading{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:22px}.profile-heading h2{font-weight:700;margin:0}.profile-heading p{color:#718096;margin:5px 0 0}.profile-summary,.profile-card{border-radius:17px;overflow:hidden}.profile-avatar{width:88px;height:88px;border-radius:50%;margin:0 auto 15px;background:linear-gradient(135deg,#0d6efd,#0f4c81);color:#fff;display:grid;place-items:center;font-size:34px;font-weight:700;box-shadow:0 9px 22px rgba(13,110,253,.22)}.account-state{display:inline-flex;align-items:center;gap:6px;padding:6px 11px;border-radius:20px;background:#ecfdf5;color:#166534;font-size:12px;font-weight:600}.summary-details{text-align:left}.summary-details>div{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid #edf1f5;font-size:12px}.summary-details span{color:#8491a3}.profile-stats{display:grid;grid-template-columns:repeat(3,1fr);background:#fff;border:1px solid #e5eaf0;border-radius:14px;overflow:hidden}.profile-stats>div{text-align:center;padding:14px 6px;border-right:1px solid #e5eaf0}.profile-stats>div:last-child{border:0}.profile-stats strong,.profile-stats span{display:block}.profile-stats strong{font-size:20px;color:#0f4c81}.profile-stats span{font-size:10px;color:#8491a3}.profile-card .form-label{font-size:13px;font-weight:600}.profile-card .form-control{min-height:47px;border-radius:11px;border-color:#dbe2ea}.profile-card textarea.form-control{min-height:90px}@media(max-width:576px){.profile-heading{align-items:flex-start;flex-direction:column}.profile-card .card-header,.profile-card .card-body{padding:18px!important}}
</style>@endpush
@push('styles')<style>.profile-avatar{width:112px;height:112px;overflow:hidden;border:4px solid #fff;font-size:40px}.profile-avatar img{width:100%;height:100%;object-fit:cover}.photo-actions{display:flex;justify-content:center;gap:7px}.photo-actions form{margin:0}.photo-actions .btn{border-radius:9px}.profile-email{overflow-wrap:anywhere}</style>@endpush
