@php($editing=isset($surat))
@if($errors->any())<div class="alert alert-danger"><strong>Periksa kembali data surat.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($editing && $surat->status==='dikembalikan' && $surat->catatan_admin)<div class="alert alert-danger"><strong>Catatan Admin</strong><div>{{ $surat->catatan_admin }}</div></div>@endif
<section class="outgoing-section"><div class="section-heading"><span><i class="bi bi-envelope-paper"></i></span><div><h4>Identitas Surat</h4><p>Lengkapi nomor, tanggal, tujuan, dan perihal surat keluar.</p></div></div><div class="row g-3">
    <div class="col-md-6"><label class="form-label">Nomor Surat <b class="text-danger">*</b></label><input name="nomor_surat" value="{{ old('nomor_surat',$surat->nomor_surat ?? '') }}" maxlength="100" class="form-control @error('nomor_surat') is-invalid @enderror" required>@error('nomor_surat')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Tanggal Surat <b class="text-danger">*</b></label><input type="date" name="tanggal_surat" value="{{ old('tanggal_surat',isset($surat)?$surat->tanggal_surat?->format('Y-m-d'):now()->format('Y-m-d')) }}" class="form-control @error('tanggal_surat') is-invalid @enderror" required>@error('tanggal_surat')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Kode Surat</label><input name="kode_surat" value="{{ old('kode_surat',$surat->kode_surat ?? '') }}" maxlength="50" class="form-control @error('kode_surat') is-invalid @enderror">@error('kode_surat')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-8"><label class="form-label">Tujuan Surat/Instansi <b class="text-danger">*</b></label><input name="tujuan_surat" value="{{ old('tujuan_surat',$surat->tujuan_surat ?? '') }}" maxlength="255" class="form-control @error('tujuan_surat') is-invalid @enderror" required>@error('tujuan_surat')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label">Perihal <b class="text-danger">*</b></label><input name="perihal" value="{{ old('perihal',$surat->perihal ?? '') }}" maxlength="500" class="form-control @error('perihal') is-invalid @enderror" required>@error('perihal')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div></section>
<section class="outgoing-section"><div class="section-heading"><span><i class="bi bi-pen"></i></span><div><h4>Penandatangan dan Isi</h4><p>Pilih pegawai yang memiliki jabatan sebagai penandatangan.</p></div></div><div class="row g-3">
    <div class="col-12"><label class="form-label">Pimpinan/Penandatangan <b class="text-danger">*</b></label><select name="pimpinan_pegawai_id" class="form-select @error('pimpinan_pegawai_id') is-invalid @enderror" required><option value="">Pilih Penandatangan</option>@foreach($pimpinans as $pimpinan)<option value="{{ $pimpinan->id }}" @selected((string)old('pimpinan_pegawai_id',$selectedPimpinanId ?? '')===(string)$pimpinan->id)>{{ $pimpinan->nama }} — {{ $pimpinan->jabatan?->nama }}</option>@endforeach</select>@error('pimpinan_pegawai_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label">Deskripsi/Isi Ringkas</label><textarea name="deskripsi" rows="6" maxlength="2000" class="form-control @error('deskripsi') is-invalid @enderror">{{ old('deskripsi',$surat->deskripsi ?? '') }}</textarea>@error('deskripsi')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div></section>
<section class="outgoing-section"><div class="section-heading"><span><i class="bi bi-paperclip"></i></span><div><h4>Lampiran</h4><p>Unggah dokumen surat atau biarkan kosong.</p></div></div>@if($editing && $surat->file_path)<div class="current-file"><i class="bi bi-file-earmark-check"></i><div><strong>Lampiran saat ini</strong><small>{{ basename($surat->file_path) }}</small></div><a href="{{ route('surat.lampiran',$surat) }}" class="btn btn-sm btn-outline-primary">Lihat</a></div>@endif<div class="mt-3"><input type="file" name="file_path" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" class="form-control @error('file_path') is-invalid @enderror"><small class="text-muted">PDF, DOC, DOCX, JPG, JPEG, atau PNG sesuai batas upload sistem.</small>@error('file_path')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></section>
<div class="workflow-note"><i class="bi bi-shield-check"></i><span>{{ $editing?'Simpan perubahan lalu kirim kembali dari tabel atau halaman detail.':'Simpan sebagai draft untuk dilanjutkan nanti, atau langsung kirim ke Admin.' }}</span></div>
<div class="outgoing-actions"><a href="{{ route('pegawai.surat-keluar.index') }}" class="btn btn-light border">Batal</a>@if($editing)<button class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan Perubahan</button>@else<button name="status" value="draft" class="btn btn-outline-primary"><i class="bi bi-file-earmark me-2"></i>Simpan Draft</button><button name="status" value="diajukan" class="btn btn-primary"><i class="bi bi-send me-2"></i>Simpan &amp; Kirim ke Admin</button>@endif</div>
@once @push('styles')<style>.outgoing-form{max-width:1050px;margin:auto}.outgoing-section{background:#fff;border:1px solid #e5ebf2;border-radius:18px;padding:25px;margin-bottom:18px;box-shadow:0 8px 24px rgba(15,76,129,.05)}.section-heading{display:flex;align-items:center;gap:13px;padding-bottom:16px;margin-bottom:18px;border-bottom:1px solid #edf1f5}.section-heading>span{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;background:#eaf3fb;color:#0f4c81}.section-heading h4{font-size:18px;margin:0}.section-heading p{margin:2px 0 0;color:#64748b}.outgoing-form .form-label{font-weight:650}.outgoing-form .form-control,.outgoing-form .form-select{min-height:48px;border-radius:11px}.current-file{display:flex;align-items:center;gap:12px;padding:14px;border-radius:12px;background:#f4f8fc}.current-file>i{font-size:25px;color:#15803d}.current-file>div{flex:1}.current-file strong,.current-file small{display:block}.workflow-note{display:flex;gap:10px;padding:15px;border-radius:12px;background:#eaf3fb;color:#174b75;margin-bottom:18px}.outgoing-actions{display:flex;justify-content:flex-end;gap:10px;padding-bottom:22px}@media(max-width:600px){.outgoing-section{padding:20px}.outgoing-actions{flex-direction:column-reverse}}</style>@endpush @endonce
