@extends('layouts.pegawai')
@section('title','Surat Keluar')
@section('content')
<div class="container-fluid employee-page">
    <div class="page-header"><div><h2><i class="bi bi-envelope-arrow-up-fill text-primary me-2"></i>Surat Keluar</h2><p class="text-muted mb-0">Buat surat, pantau proses Admin, dan kelola perbaikannya.</p></div><a href="{{ route('pegawai.surat-keluar.create') }}" class="btn btn-primary"><i class="bi bi-plus-circle me-2"></i>Tambah Surat Keluar</a></div>
    <div class="metric-grid">@foreach([['Total',$stats['total'],'bi-files','primary'],['Draft',$stats['draft'],'bi-file-earmark','secondary'],['Dalam Proses',$stats['diajukan'],'bi-hourglass-split','warning'],['Perlu Perbaikan',$stats['perbaikan'],'bi-exclamation-triangle','danger'],['Selesai',$stats['selesai'],'bi-check-circle','success']] as [$label,$value,$icon,$color])<div class="metric-card"><span class="metric-icon bg-{{ $color }}-subtle text-{{ $color }}"><i class="bi {{ $icon }}"></i></span><div><strong>{{ $value }}</strong><small>{{ $label }}</small></div></div>@endforeach</div>
    <div class="data-card">
        <form method="GET" class="filter-bar"><div class="search-control"><i class="bi bi-search"></i><input name="keyword" value="{{ request('keyword') }}" placeholder="Cari nomor, perihal, atau tujuan surat"></div><select name="status"><option value="">Semua status</option>@foreach(['draft'=>'Draft','diajukan'=>'Diajukan ke Admin','diverifikasi'=>'Diverifikasi','dikembalikan'=>'Perlu Perbaikan','diteruskan_ke_pimpinan'=>'Diteruskan ke Pimpinan','terkirim'=>'Terkirim','diarsipkan'=>'Diarsipkan'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i>Filter</button>@if(request()->hasAny(['keyword','status']))<a href="{{ route('pegawai.surat-keluar.index') }}" class="btn btn-outline-secondary"><i class="bi bi-x-lg"></i></a>@endif</form>
        <div class="table-responsive"><table class="table compact-table outgoing-table mb-0"><thead><tr><th>No</th><th>Nomor &amp; Perihal</th><th>Tujuan</th><th>Penandatangan</th><th>Tanggal</th><th>Lampiran</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
        @forelse($surat as $item)<tr>
            <td>{{ $surat->firstItem()+$loop->index }}</td><td><span class="cell-title">{{ $item->nomor_surat }}</span><span class="cell-meta">{{ $item->perihal }}</span>@if($item->kode_surat)<span class="code-chip">{{ $item->kode_surat }}</span>@endif</td>
            <td>{{ $item->tujuan_surat ?: '-' }}</td><td><span class="cell-title">{{ $item->nama_pimpinan ?: '-' }}</span><span class="cell-meta">{{ $item->jabatanPimpinan?->nama ?? 'Jabatan belum tersedia' }}</span></td>
            <td><span class="cell-title">{{ $item->tanggal_surat?->translatedFormat('d M Y') }}</span><span class="cell-meta">Diubah {{ $item->updated_at->diffForHumans() }}</span></td>
            <td>@if($item->file_path)<a href="{{ route('surat.lampiran',$item) }}" class="attachment-chip"><i class="bi bi-paperclip"></i>{{ strtoupper(pathinfo($item->file_path,PATHINFO_EXTENSION)) }}</a>@else<span class="cell-meta">Tidak ada</span>@endif</td>
            <td><span class="badge rounded-pill bg-{{ $item->status_badge }}">{{ $item->status_label }}</span>@if($item->catatan_admin)<span class="cell-meta text-danger" title="{{ $item->catatan_admin }}">Catatan: {{ Str::limit($item->catatan_admin,40) }}</span>@endif</td>
            <td><div class="row-actions"><a href="{{ route('pegawai.surat-keluar.show',$item) }}" class="btn btn-outline-primary" title="Detail"><i class="bi bi-eye"></i></a>@if(in_array($item->status,['draft','dikembalikan','Menunggu']))<a href="{{ route('pegawai.surat-keluar.edit',$item) }}" class="btn btn-outline-warning" title="Edit"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('pegawai.surat-keluar.kirim',$item) }}" onsubmit="return confirm('Kirim surat ke Admin?')">@csrf @method('PUT')<button class="btn btn-outline-success" title="Kirim"><i class="bi bi-send"></i></button></form><form method="POST" action="{{ route('pegawai.surat-keluar.destroy',$item) }}" onsubmit="return confirm('Pindahkan surat ini ke sampah?')">@csrf @method('DELETE')<button class="btn btn-outline-danger" title="Hapus"><i class="bi bi-trash"></i></button></form>@endif</div></td>
        </tr>@empty<tr><td colspan="8"><div class="empty-state"><i class="bi bi-send"></i><h5>Belum ada surat keluar</h5><p>Buat surat baru atau ubah filter pencarian.</p></div></td></tr>@endforelse
        </tbody></table></div><div class="data-footer"><span>{{ $surat->firstItem() ?? 0 }}&ndash;{{ $surat->lastItem() ?? 0 }} dari {{ $surat->total() }} surat</span>{{ $surat->links() }}</div>
    </div>
</div>
@endsection
@push('styles')<style>.outgoing-table{min-width:1220px}.attachment-chip,.code-chip{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border-radius:8px;background:#eaf3fb;color:#0f4c81;text-decoration:none;font-size:11px;font-weight:700}.code-chip{margin-top:5px;background:#f1f5f9;color:#475569}</style>@endpush
