@extends('layouts.pegawai')
@section('title','Detail Surat Keluar')
@section('content')
<div class="page-header"><div><h2><i class="bi bi-envelope-paper-fill text-primary me-2"></i>Detail Surat Keluar</h2><p class="text-muted mb-0">Informasi surat, status proses, lampiran, dan riwayat aktivitas.</p></div><a href="{{ route('pegawai.surat-keluar.index') }}" class="btn btn-light border">Kembali</a></div>
<div class="outgoing-summary"><div><small>Nomor Surat</small><h3>{{ $surat->nomor_surat }}</h3><p>{{ $surat->perihal }}</p></div><span class="badge bg-{{ $surat->status_badge }}">{{ $surat->status_label }}</span></div>
@if($surat->catatan_admin)<div class="alert alert-danger"><strong><i class="bi bi-chat-left-text me-2"></i>Catatan Admin</strong><div>{{ $surat->catatan_admin }}</div></div>@endif
<div class="row g-4">
    <div class="col-lg-8">
        <div class="detail-card"><div class="card-heading"><h4>Informasi Surat</h4></div><div class="detail-grid">@foreach([
            ['Tanggal Surat',$surat->tanggal_surat?->translatedFormat('d F Y'),'calendar-event'],
            ['Kode Surat',$surat->kode_surat ?: '-','upc-scan'],
            ['Tujuan Surat',$surat->tujuan_surat ?: '-','building'],
            ['Penandatangan',$surat->nama_pimpinan ?: '-','person-check'],
            ['Jabatan Penandatangan',$surat->jabatanPimpinan?->nama ?? '-','person-badge'],
            ['Terakhir Diubah',$surat->updated_at->translatedFormat('d F Y H:i'),'clock-history'],
        ] as [$label,$value,$icon])<div><span><i class="bi bi-{{ $icon }}"></i></span><section><small>{{ $label }}</small><strong>{{ $value }}</strong></section></div>@endforeach</div><div class="description-box"><small>Deskripsi/Isi Ringkas</small><p>{{ $surat->deskripsi ?: 'Tidak ada deskripsi.' }}</p></div></div>
        <div class="detail-card mt-4"><div class="card-heading"><h4>Riwayat Aktivitas</h4></div><div class="activity-list">@forelse($surat->logs as $log)<div><span><i class="bi bi-clock"></i></span><section><strong>{{ $log->action }}</strong><p>{{ $log->description ?: '-' }}</p><small>{{ $log->created_at->translatedFormat('d F Y H:i') }} · {{ $log->user?->name ?? 'Sistem' }}</small></section></div>@empty<div class="text-muted p-4">Belum ada riwayat aktivitas.</div>@endforelse</div></div>
    </div>
    <div class="col-lg-4">
        <div class="detail-card"><div class="card-heading"><h4>Lampiran</h4></div><div class="attachment-panel">@if($surat->file_path)<i class="bi bi-file-earmark-check"></i><strong>{{ basename($surat->file_path) }}</strong><small>{{ strtoupper(pathinfo($surat->file_path,PATHINFO_EXTENSION)) }}</small><a href="{{ route('surat.lampiran',$surat) }}" class="btn btn-primary w-100"><i class="bi bi-download me-2"></i>Lihat / Download</a>@else<i class="bi bi-file-earmark-x text-muted"></i><span>Tidak ada lampiran</span>@endif</div></div>
        <div class="detail-card mt-4"><div class="card-heading"><h4>Aksi</h4></div><div class="action-panel"><a href="{{ route('pegawai.surat-keluar.cetak',$surat) }}" target="_blank" class="btn btn-outline-dark"><i class="bi bi-printer me-2"></i>Cetak</a>@if(in_array($surat->status,['draft','dikembalikan','Menunggu']))<a href="{{ route('pegawai.surat-keluar.edit',$surat) }}" class="btn btn-warning"><i class="bi bi-pencil me-2"></i>Edit</a><form method="POST" action="{{ route('pegawai.surat-keluar.kirim',$surat) }}" onsubmit="return confirm('Kirim surat ke Admin?')">@csrf @method('PUT')<button class="btn btn-success w-100"><i class="bi bi-send me-2"></i>Kirim ke Admin</button></form><form method="POST" action="{{ route('pegawai.surat-keluar.destroy',$surat) }}" onsubmit="return confirm('Pindahkan surat ke sampah?')">@csrf @method('DELETE')<button class="btn btn-outline-danger w-100"><i class="bi bi-trash me-2"></i>Hapus</button></form>@else<div class="locked-note"><i class="bi bi-lock"></i>Surat terkunci selama diproses.</div>@endif</div></div>
    </div>
</div>
@endsection
@push('styles')<style>.outgoing-summary,.detail-card{background:#fff;border:1px solid #e5ebf2;border-radius:19px;box-shadow:0 8px 25px rgba(15,76,129,.06)}.outgoing-summary{display:flex;align-items:center;justify-content:space-between;padding:23px 26px;margin-bottom:20px}.outgoing-summary small,.outgoing-summary h3,.outgoing-summary p{display:block;margin:0}.outgoing-summary small{color:#64748b}.outgoing-summary h3{font-size:22px}.detail-card{overflow:hidden}.card-heading{padding:18px 22px;border-bottom:1px solid #edf1f5}.card-heading h4{font-size:17px;margin:0}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:22px}.detail-grid>div{display:flex;align-items:center;gap:11px;padding:13px;border:1px solid #e7edf4;border-radius:12px}.detail-grid>div>span{width:37px;height:37px;display:grid;place-items:center;border-radius:9px;background:#eaf3fb;color:#0f4c81}.detail-grid small,.detail-grid strong{display:block}.detail-grid small,.description-box small{color:#64748b}.description-box{margin:0 22px 22px;padding:16px;background:#f7f9fc;border-radius:12px}.description-box p{white-space:pre-wrap;margin:5px 0 0}.attachment-panel,.action-panel{padding:22px;display:flex;flex-direction:column;gap:11px;text-align:center}.attachment-panel>i{font-size:45px;color:#15803d}.attachment-panel strong,.attachment-panel small{display:block}.activity-list>div{display:flex;gap:12px;padding:16px 22px;border-bottom:1px solid #edf1f5}.activity-list>div:last-child{border:0}.activity-list>div>span{width:35px;height:35px;display:grid;place-items:center;border-radius:50%;background:#eaf3fb;color:#0f4c81}.activity-list section{flex:1}.activity-list p{margin:3px 0}.activity-list small{color:#64748b}.action-panel form{margin:0}.locked-note{padding:12px;border-radius:10px;background:#f1f5f9;color:#64748b}@media(max-width:650px){.detail-grid{grid-template-columns:1fr}.outgoing-summary{align-items:flex-start;gap:12px;flex-direction:column}}</style>@endpush
