@php($current = $jabatan ?? null)
@if($errors->any())<div class="alert alert-danger"><strong>Periksa kembali data jabatan.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="position-form-card">
    <div class="form-heading"><span><i class="bi bi-briefcase"></i></span><div><h4>Informasi Jabatan</h4><p>Kode membantu pencarian; nama jabatan wajib dan harus unik.</p></div></div>
    <div class="row g-3">
        <div class="col-md-4"><label class="form-label">Kode Jabatan</label><input name="kode" value="{{ old('kode',$current?->kode) }}" class="form-control @error('kode') is-invalid @enderror" placeholder="Contoh: KABAG" maxlength="30"><small class="form-text">Huruf, angka, “-”, atau “_”.</small>@error('kode')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-8"><label class="form-label">Nama Jabatan <span class="text-danger">*</span></label><input name="nama" value="{{ old('nama',$current?->nama) }}" class="form-control @error('nama') is-invalid @enderror" placeholder="Contoh: Kepala Bagian Administrasi" maxlength="150" required>@error('nama')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label">Deskripsi</label><textarea name="deskripsi" rows="5" maxlength="1000" class="form-control @error('deskripsi') is-invalid @enderror" placeholder="Jelaskan fungsi atau ruang lingkup jabatan">{{ old('deskripsi',$current?->deskripsi) }}</textarea><div class="form-hint"><span>Opsional, maksimal 1.000 karakter.</span><span id="descriptionCount">0/1000</span></div>@error('deskripsi')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div>
    <div class="form-note"><i class="bi bi-info-circle"></i><span>Jabatan yang sudah digunakan pegawai tetap dapat diperbarui, tetapi tidak dapat dihapus.</span></div>
    <div class="form-actions"><a href="{{ route('admin.jabatan.index') }}" class="btn btn-light border">Batal</a><button class="btn btn-primary" type="submit"><i class="bi bi-save me-2"></i>{{ $editing ? 'Simpan Perubahan' : 'Simpan Jabatan' }}</button></div>
</div>
@once
@push('styles')<style>.position-form{max-width:920px;margin:0 auto}.position-form-card{background:#fff;border:1px solid #e5eaf0;border-radius:18px;padding:28px;box-shadow:0 9px 26px rgba(15,76,129,.06)}.form-heading{display:flex;gap:14px;align-items:center;padding-bottom:19px;margin-bottom:22px;border-bottom:1px solid #edf1f5}.form-heading>span{width:44px;height:44px;border-radius:12px;background:#edf6ff;color:#0f4c81;display:grid;place-items:center;font-size:20px}.form-heading h4{margin:0 0 3px;font-size:19px;font-weight:700}.form-heading p{margin:0;color:#718096;font-size:13px}.position-form .form-label{font-weight:650;color:#334155}.position-form .form-control{min-height:48px;border-color:#dbe2ea;border-radius:11px}.position-form textarea.form-control{min-height:130px}.position-form .form-text,.form-hint{font-size:12px;color:#8491a3;margin-top:5px}.form-hint{display:flex;justify-content:space-between}.form-note{display:flex;gap:9px;padding:14px;margin-top:22px;background:#edf6ff;color:#174b75;border-radius:11px;font-size:13px}.form-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:22px}.form-actions .btn{min-width:155px;border-radius:10px}@media(max-width:600px){.position-form-card{padding:20px}.form-actions{flex-direction:column-reverse}.form-actions .btn{width:100%}}</style>@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const field=document.querySelector('textarea[name="deskripsi"]'),counter=document.getElementById('descriptionCount');if(!field||!counter)return;const update=()=>counter.textContent=`${field.value.length}/1000`;field.addEventListener('input',update);update();});</script>@endpush
@endonce
