@php($editing=isset($disposisi))
@if($errors->any())<div class="alert alert-danger"><strong>Periksa kembali data disposisi.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="employee-disposition-form">
    <div class="form-heading"><span><i class="bi bi-send-check"></i></span><div><h4>Informasi Disposisi</h4><p>Hanya surat yang dapat Anda akses dan sudah diverifikasi yang tersedia.</p></div></div>
    <div class="row g-3">
        <div class="col-12"><label class="form-label">Surat <b class="text-danger">*</b></label><select name="surat_id" class="form-select @error('surat_id') is-invalid @enderror" required><option value="">Pilih Surat</option>@foreach($surat as $item)<option value="{{ $item->id }}" @selected((string)old('surat_id',$disposisi->surat_id ?? '')===(string)$item->id)>{{ $item->nomor_surat }} — {{ $item->perihal }}</option>@endforeach</select>@error('surat_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label">Pegawai Penerima <b class="text-danger">*</b></label><select name="pegawai_id[]" class="form-select @error('pegawai_id') is-invalid @enderror" multiple required>@foreach($pegawai as $item)<option value="{{ $item->id }}" @selected(in_array($item->id,old('pegawai_id',$pegawaiDipilih ?? [])))>{{ $item->nama }} — {{ $item->jabatan?->nama ?? 'Tanpa jabatan' }} / {{ $item->unitKerja?->nama ?? 'Tanpa unit' }}</option>@endforeach</select>@error('pegawai_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label">Prioritas <b class="text-danger">*</b></label><select name="prioritas" class="form-select" required>@foreach(['Rendah','Sedang','Tinggi'] as $value)<option value="{{ $value }}" @selected(old('prioritas',$disposisi->prioritas ?? 'Sedang')===$value)>{{ $value }}</option>@endforeach</select></div>
        <div class="col-md-6"><label class="form-label">Tanggal Disposisi <b class="text-danger">*</b></label><input type="date" name="tanggal_disposisi" value="{{ old('tanggal_disposisi',isset($disposisi)?$disposisi->tanggal_disposisi?->format('Y-m-d'):now()->format('Y-m-d')) }}" class="form-control" required></div>
        <div class="col-12"><label class="form-label">Instruksi <b class="text-danger">*</b></label><textarea name="catatan" rows="6" maxlength="2000" class="form-control @error('catatan') is-invalid @enderror" required>{{ old('catatan',$disposisi->catatan ?? '') }}</textarea><small class="text-muted">Maksimal 2.000 karakter.</small>@error('catatan')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div>
    <div class="form-note"><i class="bi bi-shield-lock"></i><span>Disposisi hanya dapat diedit atau dihapus selama seluruh penerima belum membacanya.</span></div>
    <div class="form-actions"><a href="{{ route('pegawai.disposisi.index') }}" class="btn btn-light border">Batal</a><button class="btn btn-primary"><i class="bi bi-send me-2"></i>{{ $editing?'Simpan Perubahan':'Kirim Disposisi' }}</button></div>
</div>
@once @push('styles')<style>.disposition-form{max-width:980px;margin:auto}.employee-disposition-form{background:#fff;border:1px solid #e5ebf2;border-radius:19px;padding:27px;box-shadow:0 9px 27px rgba(15,76,129,.06)}.form-heading{display:flex;align-items:center;gap:13px;padding-bottom:18px;margin-bottom:20px;border-bottom:1px solid #edf1f5}.form-heading>span{width:44px;height:44px;border-radius:12px;display:grid;place-items:center;background:#eaf3fb;color:#0f4c81;font-size:20px}.form-heading h4{margin:0}.form-heading p{margin:3px 0 0;color:#64748b}.disposition-form .form-label{font-weight:650}.disposition-form .form-control,.disposition-form .form-select{min-height:48px;border-radius:11px}.form-note{display:flex;gap:10px;padding:14px;margin-top:20px;border-radius:11px;background:#fff7db;color:#7c5b00}.form-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}@media(max-width:600px){.employee-disposition-form{padding:20px}.form-actions{flex-direction:column-reverse}}</style>@endpush @endonce
