@extends('layouts.pegawai')
@section('title','Detail Disposisi Terkirim')
@section('content')
<div class="page-header"><div><h2><i class="bi bi-send-check-fill text-primary me-2"></i>Detail Disposisi Terkirim</h2><p class="text-muted mb-0">Status instruksi yang Anda kirim kepada pegawai.</p></div><a href="{{ route('pegawai.disposisi.index') }}" class="btn btn-light border">Kembali</a></div>
<div class="data-card sent-detail">
    <div class="sent-summary"><div><small>Surat</small><strong>{{ $disposisi->surat?->nomor_surat ?? '-' }}</strong><span>{{ $disposisi->surat?->perihal ?? '-' }}</span></div><span class="badge bg-{{ $disposisi->prioritas==='Tinggi'?'danger':($disposisi->prioritas==='Sedang'?'warning':'secondary') }}">{{ $disposisi->prioritas }}</span></div>
    <div class="sent-body"><div class="info-grid"><div><small>Tanggal</small><strong>{{ $disposisi->tanggal_disposisi?->translatedFormat('d F Y') }}</strong></div><div><small>Pengirim</small><strong>{{ $disposisi->pengirim?->name }}</strong></div></div><div class="instruction-box"><small>Instruksi</small><p>{{ $disposisi->catatan }}</p></div>
    <h5>Penerima dan Status</h5><div class="recipient-list">@foreach($disposisi->tujuans as $tujuan)<div><span class="recipient-avatar">{{ strtoupper(mb_substr($tujuan->pegawai?->nama ?? '-',0,1)) }}</span><span><strong>{{ $tujuan->pegawai?->nama ?? '-' }}</strong><small>{{ $tujuan->pegawai?->jabatan?->nama ?? 'Tanpa jabatan' }} · {{ $tujuan->pegawai?->unitKerja?->nama ?? 'Tanpa unit' }}</small></span><span class="badge bg-{{ $tujuan->status==='Selesai'?'success':($tujuan->status==='Belum Dibaca'?'danger':'warning') }}">{{ $tujuan->status }}</span></div>@endforeach</div></div>
    <div class="sent-actions">@if($disposisi->is_editable)<form method="POST" action="{{ route('pegawai.disposisi.destroy',$disposisi) }}" onsubmit="return confirm('Hapus disposisi ini?')">@csrf @method('DELETE')<button class="btn btn-outline-danger"><i class="bi bi-trash me-2"></i>Hapus</button></form><a href="{{ route('pegawai.disposisi.edit',$disposisi) }}" class="btn btn-warning"><i class="bi bi-pencil me-2"></i>Edit</a>@else<span class="text-muted"><i class="bi bi-lock me-1"></i>Disposisi terkunci karena sudah dibaca penerima.</span>@endif</div>
</div>
@endsection
@push('styles')<style>.sent-detail{max-width:980px;margin:auto}.sent-summary,.sent-actions{padding:22px 25px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #edf1f5}.sent-summary small,.sent-summary strong,.sent-summary span{display:block}.sent-summary small,.sent-body small{color:#64748b}.sent-body{padding:25px}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.info-grid>div,.instruction-box{padding:15px;border:1px solid #e5ebf2;border-radius:12px}.info-grid strong{display:block}.instruction-box{margin:18px 0}.instruction-box p{margin:5px 0 0;white-space:pre-wrap}.recipient-list{border:1px solid #e5ebf2;border-radius:13px;overflow:hidden}.recipient-list>div{display:flex;align-items:center;gap:12px;padding:13px;border-bottom:1px solid #edf1f5}.recipient-list>div:last-child{border:0}.recipient-avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#eaf3fb;color:#0f4c81;font-weight:700}.recipient-list>div>span:nth-child(2){flex:1}.recipient-list strong,.recipient-list small{display:block}.sent-actions{border-top:1px solid #edf1f5;border-bottom:0}.sent-actions form{margin:0}@media(max-width:600px){.info-grid{grid-template-columns:1fr}}</style>@endpush
